#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moudle
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="costar")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAppliedUpdate(AppliedUpdate instance);
    partial void UpdateAppliedUpdate(AppliedUpdate instance);
    partial void DeleteAppliedUpdate(AppliedUpdate instance);
    partial void InsertStoreVariantType(StoreVariantType instance);
    partial void UpdateStoreVariantType(StoreVariantType instance);
    partial void DeleteStoreVariantType(StoreVariantType instance);
    partial void InsertStoreAnime(StoreAnime instance);
    partial void UpdateStoreAnime(StoreAnime instance);
    partial void DeleteStoreAnime(StoreAnime instance);
    partial void InsertStoreColor(StoreColor instance);
    partial void UpdateStoreColor(StoreColor instance);
    partial void DeleteStoreColor(StoreColor instance);
    partial void InsertStoreProductColor(StoreProductColor instance);
    partial void UpdateStoreProductColor(StoreProductColor instance);
    partial void DeleteStoreProductColor(StoreProductColor instance);
    partial void InsertStoreProductInventory(StoreProductInventory instance);
    partial void UpdateStoreProductInventory(StoreProductInventory instance);
    partial void DeleteStoreProductInventory(StoreProductInventory instance);
    partial void InsertStoreProduct(StoreProduct instance);
    partial void UpdateStoreProduct(StoreProduct instance);
    partial void DeleteStoreProduct(StoreProduct instance);
    partial void InsertStoreVariantTypeOption(StoreVariantTypeOption instance);
    partial void UpdateStoreVariantTypeOption(StoreVariantTypeOption instance);
    partial void DeleteStoreVariantTypeOption(StoreVariantTypeOption instance);
    partial void InsertAccountNewsletter(AccountNewsletter instance);
    partial void UpdateAccountNewsletter(AccountNewsletter instance);
    partial void DeleteAccountNewsletter(AccountNewsletter instance);
    partial void InsertNewsLetter(NewsLetter instance);
    partial void UpdateNewsLetter(NewsLetter instance);
    partial void DeleteNewsLetter(NewsLetter instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::Moudle.Properties.Settings.Default.costarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AppliedUpdate> AppliedUpdates
		{
			get
			{
				return this.GetTable<AppliedUpdate>();
			}
		}
		
		public System.Data.Linq.Table<StoreVariantType> StoreVariantTypes
		{
			get
			{
				return this.GetTable<StoreVariantType>();
			}
		}
		
		public System.Data.Linq.Table<StoreAnime> StoreAnimes
		{
			get
			{
				return this.GetTable<StoreAnime>();
			}
		}
		
		public System.Data.Linq.Table<StoreColor> StoreColors
		{
			get
			{
				return this.GetTable<StoreColor>();
			}
		}
		
		public System.Data.Linq.Table<StoreProductColor> StoreProductColors
		{
			get
			{
				return this.GetTable<StoreProductColor>();
			}
		}
		
		public System.Data.Linq.Table<StoreProductInventory> StoreProductInventories
		{
			get
			{
				return this.GetTable<StoreProductInventory>();
			}
		}
		
		public System.Data.Linq.Table<StoreProduct> StoreProducts
		{
			get
			{
				return this.GetTable<StoreProduct>();
			}
		}
		
		public System.Data.Linq.Table<StoreVariantTypeOption> StoreVariantTypeOptions
		{
			get
			{
				return this.GetTable<StoreVariantTypeOption>();
			}
		}
		
		public System.Data.Linq.Table<AccountNewsletter> AccountNewsletters
		{
			get
			{
				return this.GetTable<AccountNewsletter>();
			}
		}
		
		public System.Data.Linq.Table<NewsLetter> NewsLetters
		{
			get
			{
				return this.GetTable<NewsLetter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppliedUpdates")]
	public partial class AppliedUpdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UpdateID;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUpdateIDChanging(long value);
    partial void OnUpdateIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public AppliedUpdate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long UpdateID
		{
			get
			{
				return this._UpdateID;
			}
			set
			{
				if ((this._UpdateID != value))
				{
					this.OnUpdateIDChanging(value);
					this.SendPropertyChanging();
					this._UpdateID = value;
					this.SendPropertyChanged("UpdateID");
					this.OnUpdateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreVariantTypes")]
	public partial class StoreVariantType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _VariantTypeID;
		
		private string _GroupName;
		
		private string _Name;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntitySet<StoreProduct> _StoreProducts;
		
		private EntitySet<StoreProduct> _StoreProducts1;
		
		private EntitySet<StoreVariantTypeOption> _StoreVariantTypeOptions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVariantTypeIDChanging(long value);
    partial void OnVariantTypeIDChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreVariantType()
		{
			this._StoreProducts = new EntitySet<StoreProduct>(new Action<StoreProduct>(this.attach_StoreProducts), new Action<StoreProduct>(this.detach_StoreProducts));
			this._StoreProducts1 = new EntitySet<StoreProduct>(new Action<StoreProduct>(this.attach_StoreProducts1), new Action<StoreProduct>(this.detach_StoreProducts1));
			this._StoreVariantTypeOptions = new EntitySet<StoreVariantTypeOption>(new Action<StoreVariantTypeOption>(this.attach_StoreVariantTypeOptions), new Action<StoreVariantTypeOption>(this.detach_StoreVariantTypeOptions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariantTypeID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long VariantTypeID
		{
			get
			{
				return this._VariantTypeID;
			}
			set
			{
				if ((this._VariantTypeID != value))
				{
					this.OnVariantTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VariantTypeID = value;
					this.SendPropertyChanged("VariantTypeID");
					this.OnVariantTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreProduct", Storage="_StoreProducts", ThisKey="VariantTypeID", OtherKey="Variant1TypeID")]
		public EntitySet<StoreProduct> StoreProducts
		{
			get
			{
				return this._StoreProducts;
			}
			set
			{
				this._StoreProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreProduct1", Storage="_StoreProducts1", ThisKey="VariantTypeID", OtherKey="Variant2TypeID")]
		public EntitySet<StoreProduct> StoreProducts1
		{
			get
			{
				return this._StoreProducts1;
			}
			set
			{
				this._StoreProducts1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreVariantTypeOption", Storage="_StoreVariantTypeOptions", ThisKey="VariantTypeID", OtherKey="VariantTypeID")]
		public EntitySet<StoreVariantTypeOption> StoreVariantTypeOptions
		{
			get
			{
				return this._StoreVariantTypeOptions;
			}
			set
			{
				this._StoreVariantTypeOptions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StoreProducts(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType = this;
		}
		
		private void detach_StoreProducts(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType = null;
		}
		
		private void attach_StoreProducts1(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType1 = this;
		}
		
		private void detach_StoreProducts1(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType1 = null;
		}
		
		private void attach_StoreVariantTypeOptions(StoreVariantTypeOption entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType = this;
		}
		
		private void detach_StoreVariantTypeOptions(StoreVariantTypeOption entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreAnimes")]
	public partial class StoreAnime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnimeID;
		
		private string _AnimeName;
		
		private System.Data.Linq.Binary _TimeStamp;
		
		private EntitySet<StoreProduct> _StoreProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnimeIDChanging(int value);
    partial void OnAnimeIDChanged();
    partial void OnAnimeNameChanging(string value);
    partial void OnAnimeNameChanged();
    partial void OnTimeStampChanging(System.Data.Linq.Binary value);
    partial void OnTimeStampChanged();
    #endregion
		
		public StoreAnime()
		{
			this._StoreProducts = new EntitySet<StoreProduct>(new Action<StoreProduct>(this.attach_StoreProducts), new Action<StoreProduct>(this.detach_StoreProducts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int AnimeID
		{
			get
			{
				return this._AnimeID;
			}
			set
			{
				if ((this._AnimeID != value))
				{
					this.OnAnimeIDChanging(value);
					this.SendPropertyChanging();
					this._AnimeID = value;
					this.SendPropertyChanged("AnimeID");
					this.OnAnimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimeName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string AnimeName
		{
			get
			{
				return this._AnimeName;
			}
			set
			{
				if ((this._AnimeName != value))
				{
					this.OnAnimeNameChanging(value);
					this.SendPropertyChanging();
					this._AnimeName = value;
					this.SendPropertyChanged("AnimeName");
					this.OnAnimeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreAnime_StoreProduct", Storage="_StoreProducts", ThisKey="AnimeID", OtherKey="AnimeID")]
		public EntitySet<StoreProduct> StoreProducts
		{
			get
			{
				return this._StoreProducts;
			}
			set
			{
				this._StoreProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StoreProducts(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreAnime = this;
		}
		
		private void detach_StoreProducts(StoreProduct entity)
		{
			this.SendPropertyChanging();
			entity.StoreAnime = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreColors")]
	public partial class StoreColor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ColorID;
		
		private string _ColorName;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntitySet<StoreProductColor> _StoreProductColors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnColorIDChanging(int value);
    partial void OnColorIDChanged();
    partial void OnColorNameChanging(string value);
    partial void OnColorNameChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreColor()
		{
			this._StoreProductColors = new EntitySet<StoreProductColor>(new Action<StoreProductColor>(this.attach_StoreProductColors), new Action<StoreProductColor>(this.detach_StoreProductColors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ColorID
		{
			get
			{
				return this._ColorID;
			}
			set
			{
				if ((this._ColorID != value))
				{
					this.OnColorIDChanging(value);
					this.SendPropertyChanging();
					this._ColorID = value;
					this.SendPropertyChanged("ColorID");
					this.OnColorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorName", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string ColorName
		{
			get
			{
				return this._ColorName;
			}
			set
			{
				if ((this._ColorName != value))
				{
					this.OnColorNameChanging(value);
					this.SendPropertyChanging();
					this._ColorName = value;
					this.SendPropertyChanged("ColorName");
					this.OnColorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreColor_StoreProductColor", Storage="_StoreProductColors", ThisKey="ColorID", OtherKey="ColorID")]
		public EntitySet<StoreProductColor> StoreProductColors
		{
			get
			{
				return this._StoreProductColors;
			}
			set
			{
				this._StoreProductColors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StoreProductColors(StoreProductColor entity)
		{
			this.SendPropertyChanging();
			entity.StoreColor = this;
		}
		
		private void detach_StoreProductColors(StoreProductColor entity)
		{
			this.SendPropertyChanging();
			entity.StoreColor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreProductColors")]
	public partial class StoreProductColor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ProductID;
		
		private int _ColorID;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntityRef<StoreColor> _StoreColor;
		
		private EntityRef<StoreProduct> _StoreProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(long value);
    partial void OnProductIDChanged();
    partial void OnColorIDChanging(int value);
    partial void OnColorIDChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreProductColor()
		{
			this._StoreColor = default(EntityRef<StoreColor>);
			this._StoreProduct = default(EntityRef<StoreProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="BigInt NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public long ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._StoreProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorID", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ColorID
		{
			get
			{
				return this._ColorID;
			}
			set
			{
				if ((this._ColorID != value))
				{
					if (this._StoreColor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnColorIDChanging(value);
					this.SendPropertyChanging();
					this._ColorID = value;
					this.SendPropertyChanged("ColorID");
					this.OnColorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreColor_StoreProductColor", Storage="_StoreColor", ThisKey="ColorID", OtherKey="ColorID", IsForeignKey=true)]
		public StoreColor StoreColor
		{
			get
			{
				return this._StoreColor.Entity;
			}
			set
			{
				StoreColor previousValue = this._StoreColor.Entity;
				if (((previousValue != value) 
							|| (this._StoreColor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreColor.Entity = null;
						previousValue.StoreProductColors.Remove(this);
					}
					this._StoreColor.Entity = value;
					if ((value != null))
					{
						value.StoreProductColors.Add(this);
						this._ColorID = value.ColorID;
					}
					else
					{
						this._ColorID = default(int);
					}
					this.SendPropertyChanged("StoreColor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreProduct_StoreProductColor", Storage="_StoreProduct", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public StoreProduct StoreProduct
		{
			get
			{
				return this._StoreProduct.Entity;
			}
			set
			{
				StoreProduct previousValue = this._StoreProduct.Entity;
				if (((previousValue != value) 
							|| (this._StoreProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreProduct.Entity = null;
						previousValue.StoreProductColors.Remove(this);
					}
					this._StoreProduct.Entity = value;
					if ((value != null))
					{
						value.StoreProductColors.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(long);
					}
					this.SendPropertyChanged("StoreProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreProductInventories")]
	public partial class StoreProductInventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _InventoryID;
		
		private long _ProductID;
		
		private int _QtyAvail;
		
		private int _QtySold;
		
		private int _QtyOnHold;
		
		private int _SortOrder;
		
		private System.Nullable<long> _Variant1OptionID;
		
		private System.Nullable<long> _Variant2OptionID;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntityRef<StoreVariantTypeOption> _StoreVariantTypeOption;
		
		private EntityRef<StoreVariantTypeOption> _StoreVariantTypeOption1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInventoryIDChanging(long value);
    partial void OnInventoryIDChanged();
    partial void OnProductIDChanging(long value);
    partial void OnProductIDChanged();
    partial void OnQtyAvailChanging(int value);
    partial void OnQtyAvailChanged();
    partial void OnQtySoldChanging(int value);
    partial void OnQtySoldChanged();
    partial void OnQtyOnHoldChanging(int value);
    partial void OnQtyOnHoldChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    partial void OnVariant1OptionIDChanging(System.Nullable<long> value);
    partial void OnVariant1OptionIDChanged();
    partial void OnVariant2OptionIDChanging(System.Nullable<long> value);
    partial void OnVariant2OptionIDChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreProductInventory()
		{
			this._StoreVariantTypeOption = default(EntityRef<StoreVariantTypeOption>);
			this._StoreVariantTypeOption1 = default(EntityRef<StoreVariantTypeOption>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventoryID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long InventoryID
		{
			get
			{
				return this._InventoryID;
			}
			set
			{
				if ((this._InventoryID != value))
				{
					this.OnInventoryIDChanging(value);
					this.SendPropertyChanging();
					this._InventoryID = value;
					this.SendPropertyChanged("InventoryID");
					this.OnInventoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="BigInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public long ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyAvail", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int QtyAvail
		{
			get
			{
				return this._QtyAvail;
			}
			set
			{
				if ((this._QtyAvail != value))
				{
					this.OnQtyAvailChanging(value);
					this.SendPropertyChanging();
					this._QtyAvail = value;
					this.SendPropertyChanged("QtyAvail");
					this.OnQtyAvailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtySold", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int QtySold
		{
			get
			{
				return this._QtySold;
			}
			set
			{
				if ((this._QtySold != value))
				{
					this.OnQtySoldChanging(value);
					this.SendPropertyChanging();
					this._QtySold = value;
					this.SendPropertyChanged("QtySold");
					this.OnQtySoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyOnHold", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int QtyOnHold
		{
			get
			{
				return this._QtyOnHold;
			}
			set
			{
				if ((this._QtyOnHold != value))
				{
					this.OnQtyOnHoldChanging(value);
					this.SendPropertyChanging();
					this._QtyOnHold = value;
					this.SendPropertyChanged("QtyOnHold");
					this.OnQtyOnHoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variant1OptionID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> Variant1OptionID
		{
			get
			{
				return this._Variant1OptionID;
			}
			set
			{
				if ((this._Variant1OptionID != value))
				{
					if (this._StoreVariantTypeOption.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVariant1OptionIDChanging(value);
					this.SendPropertyChanging();
					this._Variant1OptionID = value;
					this.SendPropertyChanged("Variant1OptionID");
					this.OnVariant1OptionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variant2OptionID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> Variant2OptionID
		{
			get
			{
				return this._Variant2OptionID;
			}
			set
			{
				if ((this._Variant2OptionID != value))
				{
					if (this._StoreVariantTypeOption1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVariant2OptionIDChanging(value);
					this.SendPropertyChanging();
					this._Variant2OptionID = value;
					this.SendPropertyChanged("Variant2OptionID");
					this.OnVariant2OptionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantTypeOption_StoreProductInventory", Storage="_StoreVariantTypeOption", ThisKey="Variant1OptionID", OtherKey="VariantOptionID", IsForeignKey=true)]
		public StoreVariantTypeOption StoreVariantTypeOption
		{
			get
			{
				return this._StoreVariantTypeOption.Entity;
			}
			set
			{
				StoreVariantTypeOption previousValue = this._StoreVariantTypeOption.Entity;
				if (((previousValue != value) 
							|| (this._StoreVariantTypeOption.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreVariantTypeOption.Entity = null;
						previousValue.StoreProductInventories.Remove(this);
					}
					this._StoreVariantTypeOption.Entity = value;
					if ((value != null))
					{
						value.StoreProductInventories.Add(this);
						this._Variant1OptionID = value.VariantOptionID;
					}
					else
					{
						this._Variant1OptionID = default(Nullable<long>);
					}
					this.SendPropertyChanged("StoreVariantTypeOption");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantTypeOption_StoreProductInventory1", Storage="_StoreVariantTypeOption1", ThisKey="Variant2OptionID", OtherKey="VariantOptionID", IsForeignKey=true)]
		public StoreVariantTypeOption StoreVariantTypeOption1
		{
			get
			{
				return this._StoreVariantTypeOption1.Entity;
			}
			set
			{
				StoreVariantTypeOption previousValue = this._StoreVariantTypeOption1.Entity;
				if (((previousValue != value) 
							|| (this._StoreVariantTypeOption1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreVariantTypeOption1.Entity = null;
						previousValue.StoreProductInventories1.Remove(this);
					}
					this._StoreVariantTypeOption1.Entity = value;
					if ((value != null))
					{
						value.StoreProductInventories1.Add(this);
						this._Variant2OptionID = value.VariantOptionID;
					}
					else
					{
						this._Variant2OptionID = default(Nullable<long>);
					}
					this.SendPropertyChanged("StoreVariantTypeOption1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreProducts")]
	public partial class StoreProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ProductID;
		
		private int _AnimeID;
		
		private string _ProductCode;
		
		private string _Name;
		
		private string _Description;
		
		private string _Title;
		
		private string _PageName;
		
		private bool _IsActive;
		
		private bool _IsFeatured;
		
		private string _ImageFile;
		
		private string _ImageFile2;
		
		private string _ImageFile3;
		
		private string _ImageFile4;
		
		private System.Nullable<decimal> _RetailPrice;
		
		private decimal _SalePrice;
		
		private System.Nullable<decimal> _VIPPrice;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private System.DateTime _AddeDate;
		
		private System.Nullable<long> _Variant1TypeID;
		
		private System.Nullable<long> _Variant2TypeID;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntitySet<StoreProductColor> _StoreProductColors;
		
		private EntityRef<StoreAnime> _StoreAnime;
		
		private EntityRef<StoreVariantType> _StoreVariantType;
		
		private EntityRef<StoreVariantType> _StoreVariantType1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(long value);
    partial void OnProductIDChanged();
    partial void OnAnimeIDChanging(int value);
    partial void OnAnimeIDChanged();
    partial void OnProductCodeChanging(string value);
    partial void OnProductCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnPageNameChanging(string value);
    partial void OnPageNameChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnIsFeaturedChanging(bool value);
    partial void OnIsFeaturedChanged();
    partial void OnImageFileChanging(string value);
    partial void OnImageFileChanged();
    partial void OnImageFile2Changing(string value);
    partial void OnImageFile2Changed();
    partial void OnImageFile3Changing(string value);
    partial void OnImageFile3Changed();
    partial void OnImageFile4Changing(string value);
    partial void OnImageFile4Changed();
    partial void OnRetailPriceChanging(System.Nullable<decimal> value);
    partial void OnRetailPriceChanged();
    partial void OnSalePriceChanging(decimal value);
    partial void OnSalePriceChanged();
    partial void OnVIPPriceChanging(System.Nullable<decimal> value);
    partial void OnVIPPriceChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    partial void OnAddeDateChanging(System.DateTime value);
    partial void OnAddeDateChanged();
    partial void OnVariant1TypeIDChanging(System.Nullable<long> value);
    partial void OnVariant1TypeIDChanged();
    partial void OnVariant2TypeIDChanging(System.Nullable<long> value);
    partial void OnVariant2TypeIDChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreProduct()
		{
			this._StoreProductColors = new EntitySet<StoreProductColor>(new Action<StoreProductColor>(this.attach_StoreProductColors), new Action<StoreProductColor>(this.detach_StoreProductColors));
			this._StoreAnime = default(EntityRef<StoreAnime>);
			this._StoreVariantType = default(EntityRef<StoreVariantType>);
			this._StoreVariantType1 = default(EntityRef<StoreVariantType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimeID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AnimeID
		{
			get
			{
				return this._AnimeID;
			}
			set
			{
				if ((this._AnimeID != value))
				{
					if (this._StoreAnime.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAnimeIDChanging(value);
					this.SendPropertyChanging();
					this._AnimeID = value;
					this.SendPropertyChanged("AnimeID");
					this.OnAnimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this.OnPageNameChanging(value);
					this.SendPropertyChanging();
					this._PageName = value;
					this.SendPropertyChanged("PageName");
					this.OnPageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFeatured", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsFeatured
		{
			get
			{
				return this._IsFeatured;
			}
			set
			{
				if ((this._IsFeatured != value))
				{
					this.OnIsFeaturedChanging(value);
					this.SendPropertyChanging();
					this._IsFeatured = value;
					this.SendPropertyChanged("IsFeatured");
					this.OnIsFeaturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ImageFile
		{
			get
			{
				return this._ImageFile;
			}
			set
			{
				if ((this._ImageFile != value))
				{
					this.OnImageFileChanging(value);
					this.SendPropertyChanging();
					this._ImageFile = value;
					this.SendPropertyChanged("ImageFile");
					this.OnImageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile2", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ImageFile2
		{
			get
			{
				return this._ImageFile2;
			}
			set
			{
				if ((this._ImageFile2 != value))
				{
					this.OnImageFile2Changing(value);
					this.SendPropertyChanging();
					this._ImageFile2 = value;
					this.SendPropertyChanged("ImageFile2");
					this.OnImageFile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile3", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ImageFile3
		{
			get
			{
				return this._ImageFile3;
			}
			set
			{
				if ((this._ImageFile3 != value))
				{
					this.OnImageFile3Changing(value);
					this.SendPropertyChanging();
					this._ImageFile3 = value;
					this.SendPropertyChanged("ImageFile3");
					this.OnImageFile3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFile4", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ImageFile4
		{
			get
			{
				return this._ImageFile4;
			}
			set
			{
				if ((this._ImageFile4 != value))
				{
					this.OnImageFile4Changing(value);
					this.SendPropertyChanging();
					this._ImageFile4 = value;
					this.SendPropertyChanged("ImageFile4");
					this.OnImageFile4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetailPrice", DbType="Decimal(9,2)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> RetailPrice
		{
			get
			{
				return this._RetailPrice;
			}
			set
			{
				if ((this._RetailPrice != value))
				{
					this.OnRetailPriceChanging(value);
					this.SendPropertyChanging();
					this._RetailPrice = value;
					this.SendPropertyChanged("RetailPrice");
					this.OnRetailPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePrice", DbType="Decimal(9,2) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal SalePrice
		{
			get
			{
				return this._SalePrice;
			}
			set
			{
				if ((this._SalePrice != value))
				{
					this.OnSalePriceChanging(value);
					this.SendPropertyChanging();
					this._SalePrice = value;
					this.SendPropertyChanged("SalePrice");
					this.OnSalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPPrice", DbType="Decimal(9,2)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> VIPPrice
		{
			get
			{
				return this._VIPPrice;
			}
			set
			{
				if ((this._VIPPrice != value))
				{
					this.OnVIPPriceChanging(value);
					this.SendPropertyChanging();
					this._VIPPrice = value;
					this.SendPropertyChanged("VIPPrice");
					this.OnVIPPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddeDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime AddeDate
		{
			get
			{
				return this._AddeDate;
			}
			set
			{
				if ((this._AddeDate != value))
				{
					this.OnAddeDateChanging(value);
					this.SendPropertyChanging();
					this._AddeDate = value;
					this.SendPropertyChanged("AddeDate");
					this.OnAddeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variant1TypeID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> Variant1TypeID
		{
			get
			{
				return this._Variant1TypeID;
			}
			set
			{
				if ((this._Variant1TypeID != value))
				{
					if (this._StoreVariantType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVariant1TypeIDChanging(value);
					this.SendPropertyChanging();
					this._Variant1TypeID = value;
					this.SendPropertyChanged("Variant1TypeID");
					this.OnVariant1TypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variant2TypeID", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> Variant2TypeID
		{
			get
			{
				return this._Variant2TypeID;
			}
			set
			{
				if ((this._Variant2TypeID != value))
				{
					if (this._StoreVariantType1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVariant2TypeIDChanging(value);
					this.SendPropertyChanging();
					this._Variant2TypeID = value;
					this.SendPropertyChanged("Variant2TypeID");
					this.OnVariant2TypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreProduct_StoreProductColor", Storage="_StoreProductColors", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<StoreProductColor> StoreProductColors
		{
			get
			{
				return this._StoreProductColors;
			}
			set
			{
				this._StoreProductColors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreAnime_StoreProduct", Storage="_StoreAnime", ThisKey="AnimeID", OtherKey="AnimeID", IsForeignKey=true)]
		public StoreAnime StoreAnime
		{
			get
			{
				return this._StoreAnime.Entity;
			}
			set
			{
				StoreAnime previousValue = this._StoreAnime.Entity;
				if (((previousValue != value) 
							|| (this._StoreAnime.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreAnime.Entity = null;
						previousValue.StoreProducts.Remove(this);
					}
					this._StoreAnime.Entity = value;
					if ((value != null))
					{
						value.StoreProducts.Add(this);
						this._AnimeID = value.AnimeID;
					}
					else
					{
						this._AnimeID = default(int);
					}
					this.SendPropertyChanged("StoreAnime");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreProduct", Storage="_StoreVariantType", ThisKey="Variant1TypeID", OtherKey="VariantTypeID", IsForeignKey=true)]
		public StoreVariantType StoreVariantType
		{
			get
			{
				return this._StoreVariantType.Entity;
			}
			set
			{
				StoreVariantType previousValue = this._StoreVariantType.Entity;
				if (((previousValue != value) 
							|| (this._StoreVariantType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreVariantType.Entity = null;
						previousValue.StoreProducts.Remove(this);
					}
					this._StoreVariantType.Entity = value;
					if ((value != null))
					{
						value.StoreProducts.Add(this);
						this._Variant1TypeID = value.VariantTypeID;
					}
					else
					{
						this._Variant1TypeID = default(Nullable<long>);
					}
					this.SendPropertyChanged("StoreVariantType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreProduct1", Storage="_StoreVariantType1", ThisKey="Variant2TypeID", OtherKey="VariantTypeID", IsForeignKey=true)]
		public StoreVariantType StoreVariantType1
		{
			get
			{
				return this._StoreVariantType1.Entity;
			}
			set
			{
				StoreVariantType previousValue = this._StoreVariantType1.Entity;
				if (((previousValue != value) 
							|| (this._StoreVariantType1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreVariantType1.Entity = null;
						previousValue.StoreProducts1.Remove(this);
					}
					this._StoreVariantType1.Entity = value;
					if ((value != null))
					{
						value.StoreProducts1.Add(this);
						this._Variant2TypeID = value.VariantTypeID;
					}
					else
					{
						this._Variant2TypeID = default(Nullable<long>);
					}
					this.SendPropertyChanged("StoreVariantType1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StoreProductColors(StoreProductColor entity)
		{
			this.SendPropertyChanging();
			entity.StoreProduct = this;
		}
		
		private void detach_StoreProductColors(StoreProductColor entity)
		{
			this.SendPropertyChanging();
			entity.StoreProduct = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreVariantTypeOptions")]
	public partial class StoreVariantTypeOption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _VariantOptionID;
		
		private long _VariantTypeID;
		
		private string _Name;
		
		private int _SortOrder;
		
		private System.Data.Linq.Binary _Timestamp;
		
		private EntitySet<StoreProductInventory> _StoreProductInventories;
		
		private EntitySet<StoreProductInventory> _StoreProductInventories1;
		
		private EntityRef<StoreVariantType> _StoreVariantType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVariantOptionIDChanging(long value);
    partial void OnVariantOptionIDChanged();
    partial void OnVariantTypeIDChanging(long value);
    partial void OnVariantTypeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    partial void OnTimestampChanging(System.Data.Linq.Binary value);
    partial void OnTimestampChanged();
    #endregion
		
		public StoreVariantTypeOption()
		{
			this._StoreProductInventories = new EntitySet<StoreProductInventory>(new Action<StoreProductInventory>(this.attach_StoreProductInventories), new Action<StoreProductInventory>(this.detach_StoreProductInventories));
			this._StoreProductInventories1 = new EntitySet<StoreProductInventory>(new Action<StoreProductInventory>(this.attach_StoreProductInventories1), new Action<StoreProductInventory>(this.detach_StoreProductInventories1));
			this._StoreVariantType = default(EntityRef<StoreVariantType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariantOptionID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long VariantOptionID
		{
			get
			{
				return this._VariantOptionID;
			}
			set
			{
				if ((this._VariantOptionID != value))
				{
					this.OnVariantOptionIDChanging(value);
					this.SendPropertyChanging();
					this._VariantOptionID = value;
					this.SendPropertyChanged("VariantOptionID");
					this.OnVariantOptionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariantTypeID", DbType="BigInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public long VariantTypeID
		{
			get
			{
				return this._VariantTypeID;
			}
			set
			{
				if ((this._VariantTypeID != value))
				{
					if (this._StoreVariantType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVariantTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VariantTypeID = value;
					this.SendPropertyChanged("VariantTypeID");
					this.OnVariantTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantTypeOption_StoreProductInventory", Storage="_StoreProductInventories", ThisKey="VariantOptionID", OtherKey="Variant1OptionID")]
		public EntitySet<StoreProductInventory> StoreProductInventories
		{
			get
			{
				return this._StoreProductInventories;
			}
			set
			{
				this._StoreProductInventories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantTypeOption_StoreProductInventory1", Storage="_StoreProductInventories1", ThisKey="VariantOptionID", OtherKey="Variant2OptionID")]
		public EntitySet<StoreProductInventory> StoreProductInventories1
		{
			get
			{
				return this._StoreProductInventories1;
			}
			set
			{
				this._StoreProductInventories1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreVariantType_StoreVariantTypeOption", Storage="_StoreVariantType", ThisKey="VariantTypeID", OtherKey="VariantTypeID", IsForeignKey=true)]
		public StoreVariantType StoreVariantType
		{
			get
			{
				return this._StoreVariantType.Entity;
			}
			set
			{
				StoreVariantType previousValue = this._StoreVariantType.Entity;
				if (((previousValue != value) 
							|| (this._StoreVariantType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StoreVariantType.Entity = null;
						previousValue.StoreVariantTypeOptions.Remove(this);
					}
					this._StoreVariantType.Entity = value;
					if ((value != null))
					{
						value.StoreVariantTypeOptions.Add(this);
						this._VariantTypeID = value.VariantTypeID;
					}
					else
					{
						this._VariantTypeID = default(long);
					}
					this.SendPropertyChanged("StoreVariantType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StoreProductInventories(StoreProductInventory entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantTypeOption = this;
		}
		
		private void detach_StoreProductInventories(StoreProductInventory entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantTypeOption = null;
		}
		
		private void attach_StoreProductInventories1(StoreProductInventory entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantTypeOption1 = this;
		}
		
		private void detach_StoreProductInventories1(StoreProductInventory entity)
		{
			this.SendPropertyChanging();
			entity.StoreVariantTypeOption1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccountNewsletters")]
	public partial class AccountNewsletter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AccountID;
		
		private long _NewsletterID;
		
		private int _Opened;
		
		private System.Nullable<System.DateTime> _FirstOpenDate;
		
		private string _ErrorMessage;
		
		private bool _IsSent;
		
		private EntityRef<NewsLetter> _NewsLetter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(long value);
    partial void OnAccountIDChanged();
    partial void OnNewsletterIDChanging(long value);
    partial void OnNewsletterIDChanged();
    partial void OnOpenedChanging(int value);
    partial void OnOpenedChanged();
    partial void OnFirstOpenDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFirstOpenDateChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnIsSentChanging(bool value);
    partial void OnIsSentChanged();
    #endregion
		
		public AccountNewsletter()
		{
			this._NewsLetter = default(EntityRef<NewsLetter>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsletterID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long NewsletterID
		{
			get
			{
				return this._NewsletterID;
			}
			set
			{
				if ((this._NewsletterID != value))
				{
					if (this._NewsLetter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsletterIDChanging(value);
					this.SendPropertyChanging();
					this._NewsletterID = value;
					this.SendPropertyChanged("NewsletterID");
					this.OnNewsletterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opened", DbType="Int NOT NULL")]
		public int Opened
		{
			get
			{
				return this._Opened;
			}
			set
			{
				if ((this._Opened != value))
				{
					this.OnOpenedChanging(value);
					this.SendPropertyChanging();
					this._Opened = value;
					this.SendPropertyChanged("Opened");
					this.OnOpenedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstOpenDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FirstOpenDate
		{
			get
			{
				return this._FirstOpenDate;
			}
			set
			{
				if ((this._FirstOpenDate != value))
				{
					this.OnFirstOpenDateChanging(value);
					this.SendPropertyChanging();
					this._FirstOpenDate = value;
					this.SendPropertyChanged("FirstOpenDate");
					this.OnFirstOpenDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(250)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSent", DbType="Bit NOT NULL")]
		public bool IsSent
		{
			get
			{
				return this._IsSent;
			}
			set
			{
				if ((this._IsSent != value))
				{
					this.OnIsSentChanging(value);
					this.SendPropertyChanging();
					this._IsSent = value;
					this.SendPropertyChanged("IsSent");
					this.OnIsSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsLetter_AccountNewsletter", Storage="_NewsLetter", ThisKey="NewsletterID", OtherKey="NewsLetterID", IsForeignKey=true)]
		public NewsLetter NewsLetter
		{
			get
			{
				return this._NewsLetter.Entity;
			}
			set
			{
				NewsLetter previousValue = this._NewsLetter.Entity;
				if (((previousValue != value) 
							|| (this._NewsLetter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsLetter.Entity = null;
						previousValue.AccountNewsletters.Remove(this);
					}
					this._NewsLetter.Entity = value;
					if ((value != null))
					{
						value.AccountNewsletters.Add(this);
						this._NewsletterID = value.NewsLetterID;
					}
					else
					{
						this._NewsletterID = default(long);
					}
					this.SendPropertyChanged("NewsLetter");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsLetters")]
	public partial class NewsLetter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _NewsLetterID;
		
		private string _Subject;
		
		private string _Body;
		
		private bool _IsSent;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _SendDate;
		
		private string _CampaignCode;
		
		private EntitySet<AccountNewsletter> _AccountNewsletters;
		
		private EntityRef<NewsLetter> _NewsLetter2;
		
		private EntityRef<NewsLetter> _NewsLetter1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNewsLetterIDChanging(long value);
    partial void OnNewsLetterIDChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnIsSentChanging(bool value);
    partial void OnIsSentChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnSendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSendDateChanged();
    partial void OnCampaignCodeChanging(string value);
    partial void OnCampaignCodeChanged();
    #endregion
		
		public NewsLetter()
		{
			this._AccountNewsletters = new EntitySet<AccountNewsletter>(new Action<AccountNewsletter>(this.attach_AccountNewsletters), new Action<AccountNewsletter>(this.detach_AccountNewsletters));
			this._NewsLetter2 = default(EntityRef<NewsLetter>);
			this._NewsLetter1 = default(EntityRef<NewsLetter>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsLetterID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long NewsLetterID
		{
			get
			{
				return this._NewsLetterID;
			}
			set
			{
				if ((this._NewsLetterID != value))
				{
					if (this._NewsLetter1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsLetterIDChanging(value);
					this.SendPropertyChanging();
					this._NewsLetterID = value;
					this.SendPropertyChanged("NewsLetterID");
					this.OnNewsLetterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSent", DbType="Bit NOT NULL")]
		public bool IsSent
		{
			get
			{
				return this._IsSent;
			}
			set
			{
				if ((this._IsSent != value))
				{
					this.OnIsSentChanging(value);
					this.SendPropertyChanging();
					this._IsSent = value;
					this.SendPropertyChanged("IsSent");
					this.OnIsSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SendDate
		{
			get
			{
				return this._SendDate;
			}
			set
			{
				if ((this._SendDate != value))
				{
					this.OnSendDateChanging(value);
					this.SendPropertyChanging();
					this._SendDate = value;
					this.SendPropertyChanged("SendDate");
					this.OnSendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampaignCode", DbType="NVarChar(20)")]
		public string CampaignCode
		{
			get
			{
				return this._CampaignCode;
			}
			set
			{
				if ((this._CampaignCode != value))
				{
					this.OnCampaignCodeChanging(value);
					this.SendPropertyChanging();
					this._CampaignCode = value;
					this.SendPropertyChanged("CampaignCode");
					this.OnCampaignCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsLetter_AccountNewsletter", Storage="_AccountNewsletters", ThisKey="NewsLetterID", OtherKey="NewsletterID")]
		public EntitySet<AccountNewsletter> AccountNewsletters
		{
			get
			{
				return this._AccountNewsletters;
			}
			set
			{
				this._AccountNewsletters.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsLetter_NewsLetter", Storage="_NewsLetter2", ThisKey="NewsLetterID", OtherKey="NewsLetterID", IsUnique=true, IsForeignKey=false)]
		public NewsLetter NewsLetter2
		{
			get
			{
				return this._NewsLetter2.Entity;
			}
			set
			{
				NewsLetter previousValue = this._NewsLetter2.Entity;
				if (((previousValue != value) 
							|| (this._NewsLetter2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsLetter2.Entity = null;
						previousValue.NewsLetter1 = null;
					}
					this._NewsLetter2.Entity = value;
					if ((value != null))
					{
						value.NewsLetter1 = this;
					}
					this.SendPropertyChanged("NewsLetter2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsLetter_NewsLetter", Storage="_NewsLetter1", ThisKey="NewsLetterID", OtherKey="NewsLetterID", IsForeignKey=true)]
		public NewsLetter NewsLetter1
		{
			get
			{
				return this._NewsLetter1.Entity;
			}
			set
			{
				NewsLetter previousValue = this._NewsLetter1.Entity;
				if (((previousValue != value) 
							|| (this._NewsLetter1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsLetter1.Entity = null;
						previousValue.NewsLetter2 = null;
					}
					this._NewsLetter1.Entity = value;
					if ((value != null))
					{
						value.NewsLetter2 = this;
						this._NewsLetterID = value.NewsLetterID;
					}
					else
					{
						this._NewsLetterID = default(long);
					}
					this.SendPropertyChanged("NewsLetter1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AccountNewsletters(AccountNewsletter entity)
		{
			this.SendPropertyChanging();
			entity.NewsLetter = this;
		}
		
		private void detach_AccountNewsletters(AccountNewsletter entity)
		{
			this.SendPropertyChanging();
			entity.NewsLetter = null;
		}
	}
}
#pragma warning restore 1591
